name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Format check and fix
      run: |
        if [ "$(gofmt -s -l . | grep -v '_test.go' | wc -l)" -gt 0 ]; then
          echo "Formatting code..."
          gofmt -s -w $(find . -name '*.go' -not -name '*_test.go')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-format code"
        fi
    
    - name: Lint and fix
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --out-format=colored-line-number --fix
    
    - name: Test
      run: go test -v -race -coverprofile=coverage.out ./...
    
    - name: Coverage report
      run: go tool cover -html=coverage.out -o coverage.html
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html